services:
  - type: worker
    name: sunflower-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false

