services:
  - type: worker
    name: sunflower-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python telegram_bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8527984904:AAEZSOQ25RMpyRcsYEy1TWxiYeEbZfzDqHY
        sync: false

